Pipeline{
    agent any
    tools{
     maven 'M2_HOME'
    }
    stages{
        stage("maven-1"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
            
        }

    }
}